---
title: "DECIDE score rationale"
author: "Thomas MM; Tom A"
date: "5/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Background

Adaptive sampling is the process of optimising the distributions of gathering new data based on previously collected data. In our case, we want to use the output of current species distribution models (SDMs) to send recorders to new places that will (hopefully) improve the SDMs. From the modelling workflow that we currently have, there are two main outputs for **each species**. The first is a gridded **probability of presence** map, which ranges between 0 and 1. Where the model predicts a 0, a species is not predicted to occur; where the model predicts a 1, the species is definitely predicted to occur. The second layer is an **uncertainty** or **error** map. This is also a gridded map that ranges between 0 and 1, with higher numbers indicating regions where the model is very uncertain in its prediction, and vice versa.

######   Map of probability of presence and uncertainty layer

To create a DECIDE score across species, we first need to combine the probability of presence and uncertainty maps for each species separately to create an **adaptive sampling metric**. If we were taking a purely data-driven approach to the problem of where to send people, we would base our adaptive sampling score solely on the uncertainty map generated by the SDMs. However, many of these places are likely to have very few species present, as some of our other work has shown that model uncertainty is highest in areas with middle probability of presence values (around 0.5). However, we are trying to engage people in the process of collecting data to improve our models. This means that we need to create a score that is more sensitive to probability of presence than to uncertainty, because sending people to areas where they are unlikely to see anything could mean that people lose faith in the DECIDE project's nudges. Therefore, we need to create a score that identifies areas where: 

1. The models are the most uncertain and,
2. at least some species are likely to be present.

### Species-level adaptive sampling metric

To do this, we have chosen to combine the uncertainty and probability of presence layers by doing:

$$UncertaintyLayer * \sqrt{ProbabilityOfPresence}$$

This creates a gridded adaptive sampling map for each species, which shows us where people should go to improve each individual model.

### The cross-species DECIDE score

Once we've generated an adaptive sampling metric for each species, we then want to create a **DECIDE score** that will enable us to direct people where to sample. This is what we will show to recorders rather than a species-level DECIDE score. We have decided to combine the models across species by taking the mean of the the gridded adaptive sampling metric maps for each species weighted by the probability of presence for each species. This means that species with a very low probability of presence in a grid cell won’t contribute much to the overall DECIDE score, whereas species that are likely to be present in a grid cell will contribute more. This is important because it means that the DECIDE score won't be influenced by species that aren't likely to be present in an area. For example, Species that are restricted to the Scottish Highlands will have no (well actually, extremely little) effect on the DECIDE scores for areas around Wallingford. Figure X, shows the GB-wide DECIDE scores for moths and butterflies.




### Other points to mention

It is important to note that there are various things that can be altered or be included to modify/alter the DECIDE score.

1. This DECIDE score is based solely on the models, not user preferences and the other factors we have previously discussed 
2. Currently, the DECIDE score is completely static for this first iteration. In the final version of the app species will be toggled on and off depending on various filters. For example, species that aren't flying at the current time of year will be removed, species that are of conservation concern could be preferentially chosen, people might be able to chose 'preferred' species etc.
3. The colour scheme is still a work in progress, and can be altered to highlight the best areas.
