# smooth the recording layer generated by 'count_records'
# and use it to weight the raster provided



smooth_recording <- function(weighted_layer, # layer to be weighted
                             effort_raster, 
                             recording_impact = 10) # the larger the value the less impact it has
{
  
  smoothed_effort <- focal(x = effort_raster, 
                           w = matrix(c(0,    0.09, 0.11, 0.09,    0,
                                        0.09, 0.21, 0.33, 0.21, 0.09,
                                        0.11, 0.33,    1, 0.33, 0.11,
                                        0.09, 0.21, 0.33, 0.21, 0.09,
                                        0,    0.09, 0.11, 0.09,    0), 
                                      nrow = 5, ncol = 5),
                           pad = TRUE,
                           padValue = 0,
                           NAonly=T)
  
  # Convert recording to weighting
  weighting <- smoothed_effort
  weighting <- 1/(1+(weighting*recording_impact)) # Outputs a layer of 1s where there are no records and progressively goes to 0 where there are more records
  # have added a 1 to stop the possibility of dividing by 0
  
  # set minimum value to original layer
  M <- minValue(weighted_layer)
  
  # for now, just multiplying the weighted_layer by the weighting
  adjusted_score <- weighted_layer * weighting
  adjusted_score[adjusted_score < M] <- M # change the lowest records to be equal to the original minimum value in the area 
  
  
  return(list(weighting_layer = weighting,
              weighted_score = adjusted_score))
  
}

