---
title: "Comparing decide between locations"
author: "Thomas MM"
date: "4/8/2021"
output: html_document
---


The point of this document is to explore some potential options for creating a DECIDE score across all moth species. All plots are centred around Wallingford with a 5k radius. Models aren't the most up-to-date either, they're currently using data with replicates in each cell and aren't weighted by AUC values when combined.


```{r setup, include=F, echo = FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning=FALSE,
                      include = T)

library(spatstat)
library(tidyverse)
library(raster)
library(foreach)
library(doParallel)
library(metR)


source("../modules/filter_distance.R")
source("../modules/recommend_rank.R")
source("../modules/recommend_metric.R")
source("../modules/recommend_agg_rank.R")
source("../modules/extract_metric.R")


options(col=viridis(n = 1e4))

# unweighted geometric mean
gm_mean = function(x, na.rm=FALSE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}

# weighted geometric mean
weighted.geomean <- function(x, w, na.rm = FALSE, ...){
  return(prod(x^w, na.rm = na.rm, ...)^(1/sum(w, na.rm = na.rm, ...)))
}



```


<!-- ## Load species data -->

<!-- This code loads in data from my directory in the object store which is publicly available (as long as your notebook has access to the object store). -->

```{r species_data, echo=F, warning=FALSE, include=F}

model = c('rf', 'lr', 'gam')
taxa = 'moth'

# get a list of all the species that appear in the outputs
# these are files on the object store which is freely accessible to anyone
spp_names_lr <- unique(gsub(pattern="lr_SDMs_|_meanpred.grd|_quantilemaxmin.grd|_quantilerange.grd", replacement = '', 
                            x = list.files(paste0('/data-s3/thoval/sdm_outputs/', taxa, '/lr'), pattern = '.grd')))

spp_names_rf <- unique(gsub(pattern="rf_SDMs_|_meanpred.grd|_quantilemaxmin.grd|_quantilerange.grd", replacement = '', 
                            x = list.files(paste0('/data-s3/thoval/sdm_outputs/', taxa, '/rf'), pattern = '.grd')))

spp_names_gam <- unique(gsub(pattern="gam_SDMs_|_meanpred.grd|_quantilemaxmin.grd|_quantilerange.grd", replacement = '', 
                             x = list.files(paste0('/data-s3/thoval/sdm_outputs/', taxa, '/gam'), pattern = '.grd')))

names <- unique(c(spp_names_lr, spp_names_rf, spp_names_gam))

# sdm outputs for each species
species_stack <- list()

# error outputs
error_out <- list()

for(i in 1:length(names)){
  
  print(names[i])
  
  # initiate model list within for loop so that it gets replaced when starting a new species
  # otherwise we might get some weird overlaps
  model_stack <- list()
  errored_models <- list()
  
  for(m in 1:length(model)){
    
    check_models <- list.files(paste0('/data-s3/thoval/sdm_outputs/', taxa, '/', model[m]), 
                               pattern = paste0(names[i]),
                               full.names = TRUE)
    
    if(length(check_models)<=1){
      
      print(paste('!!!   model', model[m], 'failed for species', names[i], '  !!!'))
      
      errored_models[[m]] <- data.frame(taxa = taxa, 
                                        species = names[i], 
                                        model = model[m])
      
      next
    }
    
    # mean predictions
    mp <- list.files(paste0('/data-s3/thoval/sdm_outputs/', taxa, '/', model[m]), 
                     pattern = paste0(names[i], "_meanpred.grd"),
                     full.names = TRUE)
    
    mod_preds <- raster::stack(mp)
    names(mod_preds) <- paste0(names[i], '_', model[m],'_mean_pred')
    
    
    
    # quantile min/max
    mm <- list.files(paste0('/data-s3/thoval/sdm_outputs/', taxa, '/', model[m]), 
                     pattern = paste0(names[i], "_quantilemaxmin.grd"),
                     full.names = TRUE)
    
    qminmax <- raster::stack(mm)
    names(qminmax) <- c(paste0(names[i], '_', model[m],'_min'), paste0(names[i], '_', model[m],'_max'))
    
    
    # quantile range
    qr <- list.files(paste0('/data-s3/thoval/sdm_outputs/', taxa, '/', model[m]), 
                     pattern = paste0(names[i], "_quantilerange.grd"),
                     full.names = TRUE)
    
    qrange <- raster::stack(qr)
    names(qrange) <- paste0(names[i], '_', model[m], '_quantile_range')
    
    
    # stack all from one model together
    model_stack[[m]] <- raster::stack(mod_preds, qminmax, qrange)
    
  }
  
  # model_stack[sapply(model_stack,is.null)] <- raster(nrow=12500, 
  #                                                    ncol=7000,
  #                                                    crs="+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +units=m +no_defs")
  
  # To combine them together need to remove the NULL raster layers (i.e. if a model hasn't worked)
  model_stack <- model_stack[!sapply(model_stack,is.null)]
  
  species_stack[[i]] <- raster::stack(model_stack)
  
  # Output the models that failed too
  error_out[[i]] <- do.call('rbind', errored_models) 
  
}

# which models didn't work
errors <- do.call('rbind', error_out)
errors

# name the list entries
names(species_stack) <- names

```


<!-- ## Crop species to smaller scale -->


<!-- # ```{r cropping, echo=F, warning=FALSE, include=F} -->
<!-- #  -->
<!-- # # set location  -->
<!-- # # location = c(-2.730696, 54.026759) # quernmore -->
<!-- # # location = c(-1.110557, 51.602436) # wallingford -->
<!-- # location = c(-1.117329, 53.947566) # york -->
<!-- #  -->
<!-- # # distances -->
<!-- # distance = 5000 -->
<!-- #  -->
<!-- #  -->
<!-- # registerDoParallel(7) -->
<!-- #  -->
<!-- # # out_cropped <- list() -->
<!-- # system.time( -->
<!-- #   out_cropped <- foreach(s = 1:length(species_stack)) %dopar% { -->
<!-- #      -->
<!-- #     print(s) -->
<!-- #      -->
<!-- #     sp <- species_stack[[s]] -->
<!-- #      -->
<!-- #      -->
<!-- #     # crop the prediction -->
<!-- #     crop_pred <- filter_distance(obj = subset(sp, grep(pattern = 'mean_pred', -->
<!-- #                                                        names(sp))), -->
<!-- #                                  method = 'buffer', -->
<!-- #                                  distance = distance, -->
<!-- #                                  location = location) -->
<!-- #      -->
<!-- #     # crop the error -->
<!-- #     crop_err <- filter_distance(obj = subset(sp, grep(pattern = 'quantile_range', -->
<!-- #                                                       names(sp))), -->
<!-- #                                 method = 'buffer', -->
<!-- #                                 distance = distance, -->
<!-- #                                 location = location) -->
<!-- #      -->
<!-- #     if(length(names(crop_pred))>1){ -->
<!-- #       # get the mean -->
<!-- #       m_pred_av <- calc(crop_pred, -->
<!-- #                         mean, na.rm = T) -->
<!-- #       names(m_pred_av) <- 'predictions' -->
<!-- #        -->
<!-- #        -->
<!-- #       m_quant_av <- calc(crop_err, -->
<!-- #                          mean, na.rm = T) -->
<!-- #       names(m_quant_av) <- 'error' -->
<!-- #     } else { -->
<!-- #        -->
<!-- #       m_pred_av <- crop_err -->
<!-- #       m_quant_av <- crop_err -->
<!-- #        -->
<!-- #     } -->
<!-- #      -->
<!-- #     out_rasts <- list(m_pred_av, m_quant_av) -->
<!-- #     names(out_rasts) <- c('predictions', 'quantile_var') -->
<!-- #      -->
<!-- #     return(out_rasts) -->
<!-- #      -->
<!-- #   } -->
<!-- # ) -->
<!-- #  -->
<!-- # registerDoSEQ() -->
<!-- #  -->
<!-- # names(out_cropped) <- names -->
<!-- #  -->
<!-- # ``` -->
<!-- #  -->
<!-- #  -->
<!-- #  -->
<!-- # ```{r score_mult_spp, echo=F, warning = FALSE} -->
<!-- #  -->
<!-- # score_mult <- lapply(c(1:length(out_cropped)), FUN = function(x){ -->
<!-- #    -->
<!-- #   rm <- recommend_metric(prediction_raster = out_cropped[[x]]$predictions, -->
<!-- #                          error_raster = out_cropped[[x]]$quantile_var, -->
<!-- #                          method = 'multiply')$multiply -->
<!-- #    -->
<!-- #   return(rm) -->
<!-- #    -->
<!-- # }) -->
<!-- #  -->
<!-- # names(score_mult) <- names(out_cropped) -->
<!-- #  -->
<!-- #  -->
<!-- # # get the cropped probability of presence -->
<!-- # preds <- stack(lapply(1:length(out_cropped), FUN = function(x) out_cropped[[x]]$predictions)) -->
<!-- # names(preds) <- names(out_cropped) -->
<!-- #  -->
<!-- # # get the cropped variation -->
<!-- # var <- stack(lapply(1:length(out_cropped), FUN = function(x) out_cropped[[x]]$quantile_var)) -->
<!-- # names(var) <- names(out_cropped) -->
<!-- #  -->
<!-- #  -->
<!-- # ``` -->
<!-- #  -->
<!-- #  -->
<!-- # ```{r prb_var_rel, echo=FALSE, message = F, warning = F} -->
<!-- #  -->
<!-- # pred_df <- stack(preds) %>% as.data.frame(xy=T) %>%  -->
<!-- #   pivot_longer(cols = c(3:44), names_to = 'species_pred', values_to = 'preds') -->
<!-- # var_df <- stack(var) %>% as.data.frame(xy=T) %>%  -->
<!-- #   pivot_longer(cols = c(3:44), names_to = 'species_var', values_to = 'var') %>%  -->
<!-- #   rename(xv = x, yv = y) -->
<!-- #  -->
<!-- #  -->
<!-- # check <- (cbind(pred_df, var_df)) %>%  -->
<!-- #   na.omit() %>%  -->
<!-- #   mutate(check = ifelse(paste0(x,y,species_pred)!=paste0(xv,yv,species_var),1,0)) -->
<!-- #  -->
<!-- # head(check) -->
<!-- # #  -->
<!-- # # sum(check$check) ## all good -->
<!-- #  -->
<!-- # check %>%  -->
<!-- #   ggplot() + -->
<!-- #   # geom_point(aes(x = preds, y = var, colour = species_pred), show.legend = FALSE, alpha = 0.2) + -->
<!-- #   geom_smooth(aes(x = preds, y = var, colour = species_pred), show.legend = FALSE) + -->
<!-- #   theme_classic() + -->
<!-- #   labs(caption = 'Relationship between variation and probability of presence, coloured by species', -->
<!-- #        x = 'Predicted probability', -->
<!-- #        y = 'Variation') + -->
<!-- #   theme(plot.caption = element_text(hjust = 0, size = 12)) -->
<!-- #  -->
<!-- #  -->
<!-- # ``` -->



```{r relationship_plot_func}


plot_rel <- function(location, distance){
  
  
  registerDoParallel(7)
  
  # out_cropped <- list()
  system.time(
    out_cropped <- foreach(s = 1:length(species_stack)) %dopar% {
      
      print(s)
      
      sp <- species_stack[[s]]
      
      
      # crop the prediction
      crop_pred <- filter_distance(obj = subset(sp, grep(pattern = 'mean_pred',
                                                         names(sp))),
                                   method = 'buffer',
                                   distance = distance,
                                   location = location)
      
      # crop the error
      crop_err <- filter_distance(obj = subset(sp, grep(pattern = 'quantile_range',
                                                        names(sp))),
                                  method = 'buffer',
                                  distance = distance,
                                  location = location)
      
      if(length(names(crop_pred))>1){
        # get the mean
        m_pred_av <- calc(crop_pred,
                          mean, na.rm = T)
        names(m_pred_av) <- 'predictions'
        
        
        m_quant_av <- calc(crop_err,
                           mean, na.rm = T)
        names(m_quant_av) <- 'error'
      } else {
        
        m_pred_av <- crop_err
        m_quant_av <- crop_err
        
      }
      
      out_rasts <- list(m_pred_av, m_quant_av)
      names(out_rasts) <- c('predictions', 'quantile_var')
      
      return(out_rasts)
      
    }
  )
  
  registerDoSEQ()
  
  names(out_cropped) <- names
  
  score_mult <- lapply(c(1:length(out_cropped)), FUN = function(x){
    
    rm <- recommend_metric(prediction_raster = out_cropped[[x]]$predictions,
                           error_raster = out_cropped[[x]]$quantile_var,
                           method = 'multiply')$multiply
    
    return(rm)
    
  })
  
  names(score_mult) <- names(out_cropped)
  
  
  # get the cropped probability of presence
  preds <- stack(lapply(1:length(out_cropped), FUN = function(x) out_cropped[[x]]$predictions))
  names(preds) <- names(out_cropped)
  
  # get the cropped variation
  var <- stack(lapply(1:length(out_cropped), FUN = function(x) out_cropped[[x]]$quantile_var))
  names(var) <- names(out_cropped)
  
  
  pred_df <- stack(preds) %>% as.data.frame(xy=T) %>% 
    pivot_longer(cols = c(3:44), names_to = 'species_pred', values_to = 'preds')
  var_df <- stack(var) %>% as.data.frame(xy=T) %>% 
    pivot_longer(cols = c(3:44), names_to = 'species_var', values_to = 'var') %>% 
    rename(xv = x, yv = y)
  
  
  check <- (cbind(pred_df, var_df)) %>% 
    na.omit() %>% 
    mutate(check = ifelse(paste0(x,y,species_pred)!=paste0(xv,yv,species_var),1,0))
  
  # head(check)
  # 
  # sum(check$check) ## all good
  
  
  ## decide score image
  dec_spp <- var*sqrt(preds)
  dec <- mean(dec_spp)
  dec
  
  ## create heatmap
  grid <- expand.grid(p=seq(min(cellStats(preds, min)), max(cellStats(preds, max)), by = 0.05),
                      v=seq(min(cellStats(var, min)), max(cellStats(var, max)), by = 0.05))
  # head(grid)
  
  dec_df <- check %>% 
    mutate(dec = (var*sqrt(preds)),
           p_r = round(preds, 2),
           v_r = round(var, 2))
  # head(dec_df)
  
  grid$score <- dec_df$dec[match(paste(grid$p, grid$v), paste(dec_df$p_r, dec_df$v_r))]
  
  ht_mp <- grid %>% 
    ggplot(aes(x=p, y=v, z=score, fill = score)) +
    geom_tile() +
    geom_contour() +
    geom_label_contour() +
    scale_fill_continuous(low="yellow", high="red", 
                          guide="colorbar",na.value="transparent") +
    labs(x='predictions', 
         y='variation') +
    theme_bw()
  
  
  return(list(rast = dec,
              relationship = check %>% 
                filter(var>0) %>% 
                ggplot() +
                # geom_point(aes(x = preds, y = var, colour = species_pred), show.legend = FALSE, alpha = 0.1) +
                geom_smooth(aes(x = preds, y = var, colour = species_pred), show.legend = FALSE) +
                theme_classic() +
                labs(caption = ('Relationship between variation and probability of presence, coloured by species'),
                     x = 'Predicted probability',
                     y = 'Variation') +
                theme(plot.caption = element_text(hjust = 0, size = 12)),
              ht_map = ht_mp))
  
  
}


```


```{r loop, message=F, warning=F}

# location = c(-2.730696, 54.026759) # quernmore
# location = c(-1.110557, 51.602436) # wallingford
# location = c(-1.117329, 53.947566) # york

locations = list(quernmore = c(-2.730696, 54.026759),
                 wallingford = c(-1.110557, 51.602436),
                 # york = c(-1.117329, 53.947572),
                 pickering = c(-0.850822, 54.245236),
                 edinburgh = c(-3.223506, 55.937482),
                 loch_lom_NP = c(-4.356502, 56.346935),
                 invergarry = c(-5.018761, 57.067035),
                 quintock_hills = c(-3.137571, 51.086441))

ps <- list()

for(i in 1:length(locations)){
  
  p <- plot_rel(locations[[i]], distance = 5000)
  
  print(p[[2]] + ggtitle(paste(names(locations)[i])))
  
  ps[[i]] <- p[[2]]
  
  plot(p[[1]], main = 'arith mean of var*sqrt(mean), squared')
  
  print(p[[3]])
  
}



```




```{r heatmap_func}

knitr::knit_exit()


decide_heatmap <- function(variation, prediction, dec_place, na.rm=T){
  
  
  #### FIIIIIIIXXXXX
  variation = var[[1]]
  prediction = preds[[1]]
  dec_place = 2
  
  ## decide score image
  dec_spp <- variation*sqrt(prediction)
  dec <- mean(dec_spp)
  
  vdf <- as.data.frame(variation, xy = T)
  pdf <- as.data.frame(prediction)
  
  c_df <- cbind(vdf,pdf)
  colnames(c_df) <- c('x','y','var','pred')
  
  dec_df <- c_df %>% 
    mutate(dec = (var*sqrt(pred)),
           p_r = round(pred, dec_place),
           v_r = round(var, dec_place))

  
  ## create heatmap
  grid <- expand.grid(p=seq(cellStats(prediction, min, na.rm = na.rm), cellStats(prediction, max, na.rm = na.rm), by = as.numeric(paste0('5e-',dec_place))),
                      v=seq(cellStats(variation, min, na.rm = na.rm), cellStats(variation, max, na.rm = na.rm), by = as.numeric(paste0('5e-',dec_place))))


  grid$score <- dec_df$dec[match(paste(grid$p, grid$v), paste(dec_df$p_r, dec_df$v_r))]
  
  if(dim(grid)[1]<=1){
    
    ht_mp <- NULL
    
  } else (
  
  ht_mp <- grid %>% 
    ggplot(aes(x=p, y=v, z=score, fill = score)) +
    geom_tile() +
    geom_contour() +
    geom_label_contour() +
    scale_fill_continuous(low="yellow", high="red", 
                          guide="colorbar",na.value="transparent") +
    labs(x='predictions', 
         y='variation') +
    theme_bw()
  )
  
  return(ht_mp)
  
  
}

```


```{r, message=F}

decide_heatmap(var[[1]], preds[[1]], dec_place = 2)

# preds; var

out_ps <- lapply(1:dim(preds)[3], FUN = function(x) decide_heatmap(variation = var[[x]], prediction = preds[[x]], dec_place = 2) )

for(i in 1:length(out_ps)){
  
  print(out_ps[[i]])
  
}

```



